export const walletActions = {
  SET_ACTIVE_WALLET: "SET_ACTIVE_WALLET",
  SET_ACTIVE_CLIENT: "SET_ACTIVE_CLIENT",
  ADD_WALLET: "ADD_WALLET",
  PATH_INCREMENT: "PATH_INCREMENT",
  ADD_ACCOUNT: "ADD_ACCOUNT",
  SET_RELAYERS: "SET_RELAYERS",
  SET_SELECTED_ADDRESS: "SET_SELECTED_ADDRESS",
  SET_BACKUP_STATE: "SET_BACKUP_STATE",
  ADD_MESSAGE_TYPE: "ADD_MESSAGE_TYPE",
  SIGN_OUT: "SIGN_OUT",
  STORE_WALLETS: "STORE_WALLETS",
};

export const envActions = {
  SET_CONFIG: "SET_CONFIG",
  CONNECT: "CONNECT",
  INITIALIZE_WS_COMPLETE: "INITIALIZE_WS_COMPLETE",
  SET_WS_STATUS: "SET_WS_STATUS",
  SET_API_STATUS: "SET_API_STATUS",
  SET_RPC_STATUS: "SET_RPC_STATUS",
  SET_TX_API: "SET_TX_API",
};

export const starportActions = {
  SET_STARPORT_ENV: "SET_STARPORT_ENV",
  SET_BACKEND_RUNNING_STATES: "SET_BACKEND_RUNNING_STATES",
  SET_BACKEND_ENV: "SET_BACKEND_ENV",
  SET_PREV_STATES: "SET_PREV_STATES",
  SET_TIMER: "SET_TIMER",
  CLEAR_TIMER: "CLEAR_TIMER",
};
