// export const SET_ACTIVE_WALLET = "SET_ACTIVE_WALLET";
// export const SET_ACTIVE_CLIENT = "SET_ACTIVE_CLIENT";
// export const ADD_WALLET = "ADD_WALLET";
// export const PATH_INCREMENT = "PATH_INCREMENT";
// export const ADD_ACCOUNT = "ADD_ACCOUNT";
// export const SET_RELAYERS = "SET_RELAYERS";
// export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";
// export const SET_BACKUP_STATE = "SET_BACKUP_STATE";
// export const ADD_MESSAGE_TYPE = "ADD_MESSAGE_TYPE";
// export const SIGN_OUT = "SIGN_OUT";
// export const STORE_WALLETS = "STORE_WALLETS";

export const walletActions = {
  SET_ACTIVE_WALLET: "SET_ACTIVE_WALLET",
  SET_ACTIVE_CLIENT: "SET_ACTIVE_CLIENT",
  ADD_WALLET: "ADD_WALLET",
  PATH_INCREMENT: "PATH_INCREMENT",
  ADD_ACCOUNT: "ADD_ACCOUNT",
  SET_RELAYERS: "SET_RELAYERS",
  SET_SELECTED_ADDRESS: "SET_SELECTED_ADDRESS",
  SET_BACKUP_STATE: "SET_BACKUP_STATE",
  ADD_MESSAGE_TYPE: "ADD_MESSAGE_TYPE",
  SIGN_OUT: "SIGN_OUT",
  STORE_WALLETS: "STORE_WALLETS",
};

export const envActions = {
  SET_CONFIG: "SET_CONFIG",
  CONNECT: "CONNECT",
  INITIALIZE_WS_COMPLETE: "INITIALIZE_WS_COMPLETE",
  SET_WS_STATUS: "SET_WS_STATUS",
  SET_API_STATUS: "SET_API_STATUS",
  SET_RPC_STATUS: "SET_RPC_STATUS",
  SET_TX_API: "SET_TX_API",
};

export const starportActions = {
  SET_STARPORT_ENV: "SET_STARPORT_ENV",
  SET_BACKEND_RUNNING_STATES: "SET_BACKEND_RUNNING_STATES",
  SET_BACKEND_ENV: "SET_BACKEND_ENV",
  SET_PREV_STATES: "SET_PREV_STATES",
  SET_TIMER: "SET_TIMER",
  CLEAR_TIMER: "CLEAR_TIMER",
};
